name: Deploy AWS Image Builder

on:
  # push:
  #   branches: [ main ]
  #   paths:
  #     - 'my-app/**'
  # pull_request:
  #   branches: [ main ]
  #   paths:
  #     - 'my-app/**'
  workflow_dispatch:
    inputs:
      recipe_version:
        description: 'Recipe version to deploy'
        required: false
        default: 'latest'

env:
  AWS_REGION: ap-northeast-1

jobs:
  deploy-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aws-cdk-lib constructs boto3 pyyaml

    - name: Install CDK
      run: npm install -g aws-cdk

    - name: Deploy Image Builder Pipeline
      run: |
        cd cdk-deploy
        python cdk_deploy.py
      env:
        RECIPE_VERSION: ${{ github.event.inputs.recipe_version || 'latest' }}
        GITHUB_SHA: ${{ github.sha }}

    - name: CDK Bootstrap (if needed)
      run: |
        cd cdk-deploy
        cdk bootstrap --require-approval never
      continue-on-error: true

    - name: CDK Deploy
      run: |
        cd cdk-deploy
        cdk deploy --require-approval never
